In [1]:
import tensorflow as tf
from tensorflow import keras
from tqdm.keras import TqdmCallback

In [2]:
# creating layers
inputs = tf.keras.Input(shape=(2,), name='input')
hidden = tf.keras.layers.Dense(1, activation='sigmoid', name='hidden')(inputs)
output = tf.keras.layers.Dense(1, activation='sigmoid', name='output')(hidden)
# creating the model
model  = keras.Model(inputs, output, name='model')
# making copies of the model
nadam = tf.keras.models.clone_model(model)
adam  = tf.keras.models.clone_model(model)
sgd   = tf.keras.models.clone_model(model)

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 2)]               0         
                                                                 
 hidden (Dense)              (None, 1)                 3         
                                                                 
 output (Dense)              (None, 1)                 2         
                                                                 
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


### NAdam

In [3]:
# compiling the model
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.1)
loss      = tf.keras.losses.MeanSquaredError()
model.compile(optimizer, loss, metrics=['mae'])
model.fit([[1,2]], [0.71], epochs=15, verbose=0, callbacks=[TqdmCallback(verbose=1)])
model.predict([[1,2]])

0epoch [00:00, ?epoch/s]

0batch [00:00, ?batch/s]

1/1 [==============================] - 0s 208ms/step


array([[0.7114807]], dtype=float32)

### Adam

In [4]:
# compiling the model
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)
loss      = tf.keras.losses.MeanSquaredError()
adam.compile(optimizer, loss, metrics=['mae'])
adam.fit([[1,2]], [0.71],epochs=15, verbose=0, callbacks=[TqdmCallback(verbose=1)])
adam.predict([[1,2]])

0epoch [00:00, ?epoch/s]

0batch [00:00, ?batch/s]

1/1 [==============================] - 0s 171ms/step


array([[0.7536283]], dtype=float32)

### Stochastic Gradient Descent

In [5]:
# compiling the model
optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
loss      = tf.keras.losses.MeanSquaredError()
sgd.compile(optimizer, loss, metrics=['mae'])
sgd.fit([[1,2]], [0.71],epochs=15, verbose=0, callbacks=[TqdmCallback(verbose=1)])
sgd.predict([[1,2]])

0epoch [00:00, ?epoch/s]

0batch [00:00, ?batch/s]

1/1 [==============================] - 0s 147ms/step


array([[0.35518935]], dtype=float32)